# Test Addition Playbook for Wireframe-AI
# Automated workflow for adding tests to new features

param(
    [Parameter(Mandatory=$true)]
    [string]$FeatureName,
    [string]$TestType = "unit",
    [switch]$DryRun
)

Write-Host "🧪 Wireframe-AI Test Addition Playbook" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan

# Step 1: Identify modified files
Write-Host "`n📋 Step 1: Identifying modified files for feature '$FeatureName'..." -ForegroundColor Yellow

$gitStatus = git status --porcelain 2>$null
$modifiedFiles = @()

if ($gitStatus) {
    $modifiedRustFiles = $gitStatus | Where-Object { $_ -match '\.rs$' } | ForEach-Object {
        $_.Substring(3).Trim()
    }
    $modifiedFiles = $modifiedRustFiles
}

if ($modifiedFiles.Count -eq 0) {
    Write-Host "⚠ No modified Rust files found" -ForegroundColor Yellow
    Write-Host "Please modify some files first, or specify files manually" -ForegroundColor Yellow
    exit 0
}

Write-Host "Found $($modifiedFiles.Count) modified file(s):" -ForegroundColor Green
foreach ($file in $modifiedFiles) {
    Write-Host "  - $file" -ForegroundColor Gray
}

# Step 2: Analyze files for testable functions
Write-Host "`n📋 Step 2: Analyzing files for testable functions..." -ForegroundColor Yellow

$testableFunctions = @{}
foreach ($file in $modifiedFiles) {
    if (Test-Path $file) {
        $content = Get-Content $file -Raw
        
        # Find public functions
        $publicFunctions = [regex]::Matches($content, 'pub\s+(?:async\s+)?fn\s+(\w+)')
        if ($publicFunctions.Count -gt 0) {
            $testableFunctions[$file] = @($publicFunctions | ForEach-Object { $_.Groups[1].Value })
        }
    }
}

if ($testableFunctions.Count -eq 0) {
    Write-Host "⚠ No public functions found in modified files" -ForegroundColor Yellow
    exit 0
}

Write-Host "Found testable functions:" -ForegroundColor Green
foreach ($file in $testableFunctions.Keys) {
    Write-Host "  $file:" -ForegroundColor Yellow
    foreach ($func in $testableFunctions[$file]) {
        Write-Host "    - $func()" -ForegroundColor Gray
    }
}

# Step 3: Check for existing test files
Write-Host "`n📋 Step 3: Checking for existing test files..." -ForegroundColor Yellow

$existingTestFiles = @()
foreach ($file in $modifiedFiles) {
    $testFile = $file -replace '\.rs$', '_test.rs'
    $moduleTestFile = Join-Path (Split-Path $file) "tests" (Split-Path $file -Leaf)
    
    if (Test-Path $testFile) {
        $existingTestFiles += $testFile
    }
}

if ($existingTestFiles.Count -gt 0) {
    Write-Host "Found existing test files:" -ForegroundColor Green
    foreach ($testFile in $existingTestFiles) {
        Write-Host "  - $testFile" -ForegroundColor Gray
    }
} else {
    Write-Host "No existing test files found" -ForegroundColor Yellow
}

# Step 4: Generate test suggestions
Write-Host "`n📋 Step 4: Generating test suggestions..." -ForegroundColor Yellow

$testSuggestions = @()
foreach ($file in $testableFunctions.Keys) {
    foreach ($func in $testableFunctions[$file]) {
        $testSuggestions += @{
            File = $file
            Function = $func
            TestFile = $file -replace '\.rs$', '_test.rs'
            SuggestedTest = "#[test]
fn test_$($func.ToLower())() {
    // TODO: Implement test for $func
    assert!(true);
}"
        }
    }
}

Write-Host "Generated $($testSuggestions.Count) test suggestion(s)" -ForegroundColor Green

# Step 5: Create test files (if not dry run)
Write-Host "`n📋 Step 5: Creating test files..." -ForegroundColor Yellow

if ($DryRun) {
    Write-Host "[DRY RUN] Would create test files for:" -ForegroundColor Cyan
    foreach ($suggestion in $testSuggestions) {
        Write-Host "  - $($suggestion.TestFile)" -ForegroundColor Gray
    }
} else {
    foreach ($suggestion in $testSuggestions) {
        $testFile = $suggestion.TestFile
        
        if (-not (Test-Path $testFile)) {
            $testDir = Split-Path $testFile -Parent
            if (-not (Test-Path $testDir)) {
                New-Item -ItemType Directory -Force -Path $testDir | Out-Null
            }
            
            $testContent = @"
// Tests for $($suggestion.File)
// Auto-generated by test addition playbook

$($suggestion.SuggestedTest)
"@
            
            $testContent | Out-File $testFile -Encoding UTF8
            Write-Host "  Created: $testFile" -ForegroundColor Green
        } else {
            Write-Host "  Skipped (exists): $testFile" -ForegroundColor Yellow
        }
    }
}

# Step 6: Run tests
Write-Host "`n📋 Step 6: Running tests..." -ForegroundColor Yellow

if ($DryRun) {
    Write-Host "[DRY RUN] Would run: cargo test" -ForegroundColor Cyan
} else {
    cargo test --quiet 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "⚠ Tests failed (expected - tests are placeholders)" -ForegroundColor Yellow
        Write-Host "Implement the test functions to make them pass" -ForegroundColor Yellow
    } else {
        Write-Host "✓ Tests pass" -ForegroundColor Green
    }
}

# Step 7: Summary
Write-Host "`n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "Test Addition Summary" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "✓ Analyzed $($modifiedFiles.Count) modified file(s)" -ForegroundColor Green
Write-Host "✓ Found $($testableFunctions.Values.Count) testable function(s)" -ForegroundColor Green
Write-Host "✓ Generated $($testSuggestions.Count) test suggestion(s)" -ForegroundColor Green
Write-Host "`nNext steps:" -ForegroundColor Yellow
Write-Host "1. Implement the test functions in the generated test files" -ForegroundColor Gray
Write-Host "2. Run tests to verify they pass" -ForegroundColor Gray
Write-Host "3. Add edge cases and error scenarios" -ForegroundColor Gray
Write-Host "4. Run cargo clippy to ensure code quality" -ForegroundColor Gray
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan

exit 0
