modules:
  interface:
    enabled: true
    plugins:
      input:
        plugin_id: "input-cli"
        config:
          prompt: "wireframe> "

      output:
        plugin_id: "output-markdown"
        config:
          syntax_highlighting: true
